#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Set P4 environment variables
if [[ -s "${ZDOTDIR:-$HOME}/.p4env" ]]; then
  source "${ZDOTDIR:-$HOME}/.p4env"
fi

# Customize to your needs...
